# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-05 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_auth',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8c37\u6b4c\u4e8c\u6b21\u9a8c\u8bc1\u7801'),
        ),
    ]
